### ISSUE TITLE
remove people from group

### ISSUE THREAD

**Issue by PragTob** [rubycorns/RailsGirlsApp#300]
It might happen that people join groups but never show up, or show up and don't go to the group anymore. Members of that group might want to remove those people from the group.

**Comment by berlintam** [comment]
Just be honest Tobi. You want to kick out @FrauBienenstich , right?

**Comment by 1000miles** [comment]
+3 for this feature 

Rails Girls Berlin Project Groups Team

**Comment by berlintam** [comment]
@1000miles feel free to assign yourself (and/or your team) if you want to tackle it!

At the moment you can already [delete yourself](https://github.com/rubycorns/RailsGirlsApp/blob/master/app/controllers/registrations_controller.rb#L12), so maybe taking a look at that could be of some initial help.

**Comment by 1000miles** [comment]
Hi @berlintam,

thank you for your reply. It's not about deleting myself. This function I have already found out. It is sometimes as Tobi pointed out. 

Example:
- One day person A joined a project group but did not leave any contact data (at the moment it's only possible with twitter handle, but what if someone does not use twitter?). So there is no possibilty to get in contact with Person A.
- At the current stage of the Railsgirls App the group members don't get any notifications that someone has joined. 
- The person A never registered for the Google project group forum or never sent an email to the project group. Since weeks, months or ever.
- Then the project group is growing and it's getting full. Therefore the project group decides to close the project group. The seat of Person A is in the end reserved with never knowing if this person will ever show up or contact the project group. 

=> Maybe the person A decided to stop coding but forgot to leave the project group on her/his own? So person A will stay there as a "Karteileiche", because neither the project group nor the person A will get in contact with each other to ask. 

It is less about the power to kick-out someone because you don't like this person. I think it is more about a clear understanding for everyone (in the project group) who you can rely on to continue working with. 

---

Regarding your offer to assign myself/ourself to it. Thank you. We would love to help you with the app, but of course we wanted to find out of how much help is allowed/welcome. :)

**Comment by berlintam** [comment]
yup @1000miles i understood the initial issue idea, I just wanted to point out that some deletion of users is already in place incase you wanted to take a look. As for the @FrauBienenstich comment, I was joking. she's my roommate, and a member of our project group :)

you're always welcome to contribute to the app, please go ahead!

**Comment by 1000miles** [comment]
@berlintam okay, thanks for the clarification! ;)

"...deletion of users is already in place" - what do you mean with "in place"? You mean only the deletion of oneself, but not as an admin, right?

**Comment by berlintam** [comment]
exactly. You can delete yourself. Admins cannot delete people. Yet. :)
